name = "shipping-delay-display"
type = "checkout_ui_extension"
api_version = "2025-01"

extension_points = ["purchase.checkout.block.render"]

# Metafield access configuration
[[metafields]]
namespace = "product"
key = "shipping_delay"
